### ISSUE TITLE
better feedback to frontend when starting transcription/diarization

### ISSUE THREAD

**Issue by langemittbacken** [Racix/Project-AI-Translation#28]
as of now, the only recieved feedback is that the processing has started.

 There is a need for feedback when the analysis failed or is done.

maybe some check that only accept certain file formats to be analysed also?

when implemented frontend needs to handle this in a smart way

**Comment by IsakLundstrom** [comment]
Backend part of status feedback implemeted using websockets, frontend needs to now listen to the websocket room and show it to the user
