### ISSUE TITLE
Add delete and update buttons 

### ISSUE THREAD

**Issue by IsakLundstrom** [Racix/Project-AI-Translation#41]
Delete and update buttons need to be added to the frontend. 

- [x] Delete media file
- [x] delete analysis
- [x] patch analysis

Functionality to change text segments by hand should also be added + add functionality to only change one specific speaker, eg. if one "speaker 1" segment is clearly miss labeled it should be possible to change only that one and not all "speaker 1" segments.

**Comment by langemittbacken** [comment]
everything is added, while it may not be the most pretty solutions our goal with the frontend right now is to show of all of the backends functionalties.
