### ISSUE TITLE
Websockets when error in analyze

### ISSUE THREAD

**Issue by Lundsak** [Racix/Project-AI-Translation#48]
When analyzing and we get an error, the websocket does not get closed. I think its a frontend problem but it might be an backend problem.

_Originally posted by @Lundsak in https://github.com/Racix/Project-AI-Translation/issues/46#issuecomment-1792124428_

**Comment by Lundsak** [comment]
![image](https://github.com/Racix/Project-AI-Translation/assets/24740336/f6787e99-fab1-4fdc-8d9f-e7dfec320810)

**Comment by langemittbacken** [comment]
har nu pushat till #46 där jag ändrade logiken från att stänga när den får 201, till att stänga när statusen != 200 vilket fångar bl.a. det i bilden. 

La även till att connection stängs när analysen redan fanns, vilket vi inte gjorde tidigare
